### PR TITLE
Master revision

### PR DESCRIPTION
**Pull request by manthanand**
Finished both boards. The Bluetooth board was mounted because there were certain keep out areas that couldn't have copper in them. This also makes it less cluttered.

### CODE REVIEW

**Comment by chaseblock** [comment]
There are quite a few pins on the headers connecting the boards that are wired on the master side, but not on the BLE side. Is there a reason for that?

**Comment by chaseblock** [comment]
In addition, it looks like there's no power being fed into the BLE module.

**Comment by manthanand** [comment]
I couldn't find a footprint where there are female headers on one side and male headers on the other side, but the same size hole is used for both so I just left the female header on one side. Yes, I forgot to add power after I removed the reverse voltage protection circuit but it should be there now.

**Comment by chaseblock** [comment]
I don't quite understand what you're referencing about footprints. My question was about whether there's a reason to have 18 pins (IP0-IP17) that are not connected to anything. I could see it being somewhat useful if we want to add functionality later, but in that case, we should probably appropriately wire things on the bluetooth board as well. We may even be able to cut down on the number of wires if there are certain pins we are confident we won't need.

**Comment by manthanand** [comment]
All of those pins are for future functionality. We don't want to make a revision every time we need to add something so we are going to use those pins to add whatever we want to the board. All those pins are connected to the Bluetooth shield board. Then whenever we want to use them, we can just connect the wires. I'm not sure which pins we won't need but I don't want to take the risk of leaving some out and then finding out we might need them later on.

**Comment by manthanand** [comment]
I want to clarify that the Bluetooth board is a shield board that will be on top of the specific part of the master board. We won't be connecting wires from the master to the Bluetooth. We will just be placing it on top. Hopefully, this clears it up.

**Pull request closed without merging**
