### PR TITLE
Fan board

### PR DESCRIPTION
**Pull request by manthanand**

### CODE REVIEW

**Comment by chaseblock** [comment]
Despite the title, this pull request seems to include all of the bluetooth module additions as well. Was this intended?

**Comment by manthanand** [comment]
No, I will remove those additions

**Comment by SijWoo** [comment]
The PR has edits to some files not regarding the Fan Board so I took those out. I also moved the V2F22HM.kicad_mod footprint to the Common library folder since other boards will be using the diode besides the BPS

Some comments from me:
1. Every V2F22HM diodes' footprints need to be updated since the location changed to UTSVT_Passive.pretty (Also small note each diode's value parameter says V22F22HM instead V2F22HM)
2. The LED is facing the wrong direction. Current needs to flow from +12V to pwr gnd
3. The reference and value labels of some components need to be flipped. E.g. the 2x3 pin connector symbol has LDRBRDConn in the Reference field but it needs to be in the Value field which is currently Conn_02x03. That's why there's a number at the end of LDRBRDConn1 because that field is meant for reference labels. The references should be like how the mosfets are labeled: Q for reference and the value shows the part number.
4. I would make the area of the bottom pwrgnd plane bigger because the pwm traces are creating bottle necks, especially the left connectors can't allow as much current to flow to the mosfets compared to the right side of the board. Or even just make the plane in the whole area of the board.
*5. The distance from the left mounting hole to the left edge of the board is 10.79mm whereas the distance from the right mount holes to the right edge of the board is 11.43mm. This is just personal preference but I would rather it be symmetrical. Also I would use mm as units instead of inches when doing the spacing and board dimensions

**Comment by SijWoo** [comment]
I updated the diodes to be the correct path. Update the netlist file and the pcb so it won't have any errors. Everything looks good except I would extend the bottom copper plane (green) to be encompass the whole board. I'm sorry I wasn't clear earlier about this

**Comment by SijWoo** [comment]
Closing ticket. Fan board has been approved in BPS-FanPCB repo.

**Pull request closed without merging**
